# .github/workflows/generate-terminal-svg.yml
name: Generate Terminal SVG Animation

on:
  push:
    branches: [ main, master ]
  schedule:
    # Update every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer
        
    - name: Generate Terminal SVG
      run: |
        cat > generate-svg.js << 'EOF'
        const puppeteer = require('puppeteer');
        const fs = require('fs');
        
        async function generateTerminalSVG() {
          const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          
          const page = await browser.newPage();
          await page.setViewport({ width: 800, height: 600 });
          
          // Load your HTML content
          const htmlContent = fs.readFileSync('index.html', 'utf8');
          await page.setContent(htmlContent);
          
          // Wait for animations to complete
          await page.waitForTimeout(10000);
          
          // Take screenshot and convert to SVG-like format
          const screenshot = await page.screenshot({ 
            type: 'png',
            fullPage: true 
          });
          
          await browser.close();
          
          // Generate animated SVG
          const svgContent = generateAnimatedSVG();
          fs.writeFileSync('terminal-animation.svg', svgContent);
          
          console.log('SVG generated successfully!');
        }
        
        function generateAnimatedSVG() {
          return `<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <style>
                .terminal-bg { fill: #0c0c0c; }
                .terminal-border { fill: none; stroke: #00ffff; stroke-width: 2; }
                .text { font-family: 'Courier New', monospace; font-size: 14px; }
                .prompt { fill: #00ff88; }
                .command { fill: #00ccff; }
                .output { fill: #ffffff; }
                .cursor { fill: #00ff88; }
                .glow { filter: drop-shadow(0 0 5px currentColor); }
                
                .typing-animation {
                  animation: typing 3s steps(40, end) infinite;
                }
                
                .cursor-blink {
                  animation: blink 1s infinite;
                }
                
                .matrix-rain {
                  animation: matrix-fall 3s linear infinite;
                }
                
                @keyframes typing {
                  from { width: 0; }
                  to { width: 100%; }
                }
                
                @keyframes blink {
                  0%, 50% { opacity: 1; }
                  51%, 100% { opacity: 0; }
                }
                
                @keyframes matrix-fall {
                  0% { transform: translateY(-20px); opacity: 0; }
                  10% { opacity: 1; }
                  90% { opacity: 1; }
                  100% { transform: translateY(600px); opacity: 0; }
                }
                
                .particle {
                  animation: particle-fall 2s linear infinite;
                }
                
                @keyframes particle-fall {
                  0% { transform: translateY(-10px); opacity: 0; }
                  10% { opacity: 1; }
                  90% { opacity: 1; }
                  100% { transform: translateY(600px); opacity: 0; }
                }
              </style>
            </defs>
            
            <!-- Terminal Background -->
            <rect class="terminal-bg" width="800" height="600" rx="12"/>
            <rect class="terminal-border" width="796" height="596" x="2" y="2" rx="10"/>
            
            <!-- Terminal Header -->
            <rect fill="#333" width="800" height="40" rx="12"/>
            <circle fill="#ff5f57" cx="20" cy="20" r="6"/>
            <circle fill="#ffbd2e" cx="40" cy="20" r="6"/>
            <circle fill="#28ca42" cx="60" cy="20" r="6"/>
            <text class="text" fill="#fff" x="80" y="25">Terminal - zh13u@localhost</text>
            
            <!-- Matrix Rain Effect -->
            <g class="matrix-rain">
              <text class="text" fill="#00ff41" x="100" y="0">01010101</text>
              <animateTransform attributeName="transform" type="translate" values="0,-20; 0,600" dur="3s" repeatCount="indefinite"/>
            </g>
            <g class="matrix-rain">
              <text class="text" fill="#00ff41" x="200" y="0">11001100</text>
              <animateTransform attributeName="transform" type="translate" values="0,-20; 0,600" dur="3s" repeatCount="indefinite" begin="1s"/>
            </g>
            <g class="matrix-rain">
              <text class="text" fill="#00ff41" x="300" y="0">10101010</text>
              <animateTransform attributeName="transform" type="translate" values="0,-20; 0,600" dur="3s" repeatCount="indefinite" begin="2s"/>
            </g>
            
            <!-- Particles -->
            <g class="particle">
              <rect fill="#00ffff" width="2" height="10" x="150" y="0" opacity="0.8"/>
              <animateTransform attributeName="transform" type="translate" values="0,-10; 0,600" dur="2s" repeatCount="indefinite"/>
            </g>
            <g class="particle">
              <rect fill="#ff00ff" width="2" height="10" x="250" y="0" opacity="0.8"/>
              <animateTransform attributeName="transform" type="translate" values="0,-10; 0,600" dur="2s" repeatCount="indefinite" begin="0.5s"/>
            </g>
            
            <!-- Terminal Commands -->
            <g transform="translate(20, 70)">
              <!-- Command 1: whoami -->
              <text class="text prompt glow" x="0" y="0">root@zh13u-computer:/#</text>
              <text class="text command glow typing-animation" x="200" y="0">whoami</text>
              <text class="text cursor cursor-blink" x="270" y="0">_</text>
              <text class="text output" x="20" y="25">zh13u</text>
              
              <!-- Command 2: id -->
              <g transform="translate(0, 60)">
                <text class="text prompt glow" x="0" y="0">root@zh13u-computer:/#</text>
                <text class="text command glow typing-animation" x="200" y="0">id</text>
                <text class="text cursor cursor-blink" x="230" y="0">_</text>
                <text class="text output" x="20" y="25">root at here :)</text>
              </g>
              
              <!-- Command 3: ls -->
              <g transform="translate(0, 120)">
                <text class="text prompt glow" x="0" y="0">root@zh13u-computer:/#</text>
                <text class="text command glow typing-animation" x="200" y="0">ls</text>
                <text class="text cursor cursor-blink" x="230" y="0">_</text>
                <text class="text output" x="20" y="25">welcome</text>
              </g>
              
              <!-- Command 4: ./welcome -->
              <g transform="translate(0, 180)">
                <text class="text prompt glow" x="0" y="0">root@zh13u-computer:/#</text>
                <text class="text command glow typing-animation" x="200" y="0">./welcome</text>
                <text class="text cursor cursor-blink" x="300" y="0">_</text>
                
                <!-- Welcome Animation -->
                <g transform="translate(20, 40)">
                  <rect fill="rgba(0,0,0,0.9)" stroke="#00ffff" stroke-width="2" width="400" height="150" rx="10"/>
                  
                  <!-- ENJOY text -->
                  <text class="text" fill="url(#gradient1)" x="150" y="60" font-size="24" font-weight="bold">ENJOY</text>
                  <text class="text" fill="url(#gradient2)" x="120" y="90" font-size="18" font-weight="bold">WITH ME</text>
                  
                  <!-- Cyber icons -->
                  <text x="50" y="80" font-size="20">🔒</text>
                  <text x="320" y="60" font-size="20">🛡️</text>
                  <text x="70" y="120" font-size="20">⚡</text>
                  <text x="300" y="130" font-size="20">🔐</text>
                  
                  <!-- Animated effects -->
                  <g class="glow">
                    <animateTransform attributeName="transform" type="rotate" values="0 200 75; 360 200 75" dur="10s" repeatCount="indefinite"/>
                    <circle fill="none" stroke="#00ffff" stroke-width="1" cx="200" cy="75" r="60" opacity="0.3"/>
                  </g>
                </g>
              </g>
            </g>
            
            <!-- Gradients -->
            <defs>
              <linearGradient id="gradient1" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" style="stop-color:#ff00ff;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#00ffff;stop-opacity:1" />
              </linearGradient>
              <linearGradient id="gradient2" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" style="stop-color:#00ffff;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#ff00ff;stop-opacity:1" />
              </linearGradient>
            </defs>
            
            <!-- Glitch effect overlay -->
            <rect fill="url(#glitchPattern)" width="800" height="600" opacity="0.1">
              <animate attributeName="opacity" values="0.1;0.3;0.1" dur="2s" repeatCount="indefinite"/>
            </rect>
            
            <defs>
              <pattern id="glitchPattern" x="0" y="0" width="4" height="4" patternUnits="userSpaceOnUse">
                <rect width="4" height="2" fill="#00ffff"/>
                <rect y="2" width="4" height="2" fill="transparent"/>
              </pattern>
            </defs>
          </svg>`;
        }
        
        generateTerminalSVG().catch(console.error);
        EOF
        
        node generate-svg.js
        
    - name: Commit and Push SVG
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add terminal-animation.svg
        git diff --staged --quiet || git commit -m "🎨 Update terminal animation SVG"
        git push
